### ISSUE TITLE
Apple M1 compatibility - watch

### ISSUE THREAD

**Issue by joemaller** [ideasonpurpose/docker-phpunit-watch#1]
Trying to run this with the `watch` command fails with `entr: cannot create kqueue: Function not implemented`

Building locally on M1 works correctly, so this just needs the multi-auth code from the  [ideasonpurpose/docker-build](https://www.github.com/ideasonpurpose/docker-build) GitHub Actions

**Comment by joemaller** [comment]
Or not? It builds but doesn't seem to trigger a run on file changes

**Comment by Wowfunhappy** [comment]
Hi Joe! It looks like I forgot to turn off notifications on this repo... and then the mention of `kqueue` caught my eye. That's a particular data structure in the kernel which has, uh, caused problems for me before.

I assume `entr` is a reference to https://github.com/eradman/entr, which coincidentally uses `kqueue` to run a command when a file changes.

And the entr readme says:

> Incomplete inotify support on Windows Subsystem for Linux and Docker for Mac can cause entr to respond inconsistently. Setting the environment variable ENTR_INOTIFY_WORKAROUND will enable entr to operate in these environments.

Not sure if that helps at all, but thought I'd share!

**Comment by joemaller** [comment]
Hi Jonathan! Thanks for the info about the ENTR env var. We had something similar happen on Windows back before WSL2, but I thought Docker was mostly resolved on Apple CPUs by now.
